### ISSUE TITLE
Change library name to TelegramDB

### ISSUE THREAD

**Issue by VarnaX-279** [AnimeKaizoku/TelegramDB#1]
Already a python module `python-telegram-bot` have this name `telegram`.
![image](https://user-images.githubusercontent.com/90246361/150574777-b61ff927-8e66-4dbf-93f9-e1f77e9820fa.png)
So Change library name to anything otherwise we can't use `python-telegram-bot` and your `telegramdb` at same time or in one script

**Comment by anonyindian** [comment]
You can't use `python-telegram-bot` with the `TelegramDB` since it doesn't support bot api clients. Currently it only supports pyrogram as a telegram client, however we're planning to make it available with other clients as well soon.

**Comment by VarnaX-279** [comment]
> You can't use `python-telegram-bot` with the `TelegramDB` since it doesn't support bot api clients. Currently it only supports pyrogram as a telegram client, however we're planning to make it available with other clients as well soon.

Check this repo https://github.com/anasty17/mirror-leech-telegram-bot
Here we are using `python-telegram-bot` and `pyrogram` in one script.

**Comment by anonyindian** [comment]
> > You can't use `python-telegram-bot` with the `TelegramDB` since it doesn't support bot api clients. Currently it only supports pyrogram as a telegram client, however we're planning to make it available with other clients as well soon.
> 
> Check this repo https://github.com/anasty17/mirror-leech-telegram-bot Here we are using `python-telegram-bot` and `pyrogram` in one script.

We'll look into the matter!

**Comment by StarkBotsIndustries** [comment]
That's what I was wondering.
